---
# Playbook
- name: Create VM for app
  hosts: localhost
  vars:
    service_account_email: "devops@devopsexamproject.iam.gserviceaccount.com"
    credentials_file: "../DevopsExamProject-02241d8a5fa8.json"
    project_id: "devopsexamproject"
  tasks:

    - name: Hello, world
      shell: echo "Hello, world"

    - name: create virtual machine
      gce:
        instance_names: devops1
        zone: europe-west1-d
        machine_type: n1-standard-1
        image: debian-8
        state: present
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
        metadata : '{ "startup-script" : "apt-get update" }'
        tags:
          - http-server
          - webserver
        ip_forward: true
        service_account_permissions:
          - storage-full
          - taskqueue
          - bigquery
          - allow-internal
          - allow-ssh
        ssh_password_enabled: false
        ssh_public_keys:
          - path: "/root/.ssh/google_compute_engine"
          - key_data: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDS1FtNfZpHAaXYV5mRXSL5FfFkk4OjPQM8yO4/3DFpWRxqjCE+K2QbUJ/FJDepUam9cHGgyAiUMIllwRrgO7+HMY4Pgh9pxsoIapoJKIgidOB6M9+R5migFc8yt0eB58Oz56rCJAqflawQpNiGjgXf7vrpwWf/J6Pe4xf+DwmX5auu2lmgDWC4UYdn5g0+XMMeHEbrZHQ/xjaYWxV5hgh5yGKnvdyfd9Ejsk3tY7eeirsvnvum2VQC7s8exSQVLsJ/FpPUbeQjEAMDjNF+p0rN2GFGbeNiFgMfX3QR2lUh7wstqAFgjaLQLxKwLACv85vLnjguhYTDj4u8a4aJVm7r root@39954732a2a4"
          - path: "/root/.ssh/google-ssh-key"
          - key_data: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDA4AW3QCFlmW3hb/V5aooabyrEajeBdPj4QpU2/rQJvp2x/0cIx9/BKIL+jGkmy10g/Vh8/Q6SzcFl96w4KUYGKdJLenGgYysW2XvCGJ+V3f+oPlipI/9KP5XrvE5kPO2kCdbrs+ZHJbSnq/TIqhcNOWW8+UPB8wqNydsTqnYeSQnJycv2FMHDdlGzFPrdSV3DP7yxPs01GkTwyC4b6TBx5AqSJ/2L24oBFZAPdhJbvdIxYlm1b4xw0Ufs4rbfMJhnXa15ZWkrLJTk2ExbSrhlOOSkyWdJ3e7WzPbvXaYAqAiJ5PVn5C2cHstQB0F1GalPKm6AkGZhMiL/1jxCt3XV root"
      register: gce

    - name: Save host data
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: gce_instance_ip
      with_items: "{{ gce.instance_data }}"

    - name: Wait for SSH for instance
      wait_for:
        delay: 1
        host: "{{ item.public_ip }}"
        port: 22
        state: started
        timeout: 30
      with_items: "{{ gce.instance_data }}"

- name: Install docker on new image
  hosts: gce_instance_ip
  connection: ssh
  become: true
  tasks:
    - name: ensure repository key is installed
      apt_key:
        id: "58118E89F3A912897C070ADBF76221572C52609D"
        keyserver: "hkp://p80.pool.sks-keyservers.net:80"
        state: present

    - name: ensure docker registry is available
      # For Ubuntu 14.04 LTS, use this repository:
      apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main' state=present
      # For Ubuntu 16.04 LTS, use this repo instead:
      # apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-xenial main' state=present
      # Need to change img or find other repo..

    - name: ensure docker and dependencies are installed
      apt: name=docker-engine update_cache=yes

    - service: name=docker state=restarted

- name: Download and start container
  hosts: gce_instance_ip
  connection: ssh
  become: true

  tasks:
#    - name: log into docker hub registry
#      docker_login:
#        email: "your-email@address"
#        username: "a-dockerhub-username"
#        password: "a-dockerhub-password"

    - name: ensure a container is running
      docker_container:
        name: odeand14/devopsexam
        state: started
        image: "odeand14/devopsexam:latest"
        pull: true
        ports:
          - "80:80"
